### ISSUE TITLE
Incorrect Result for getHyperCubeData when using Master Measures in Viz Expressions

### ISSUE THREAD

**Issue by tomomni** [qlik-oss/enigma.js#944] opened 2022-02-22 17:25 UTC
### Description

Data returned is exclusively null for columns that reference master measures by name in their expression when calling getHyperCubeData on a visualization object.

### Steps to Reproduce

1. Use enigma to call getHyperCubeData on a visualization object that is referencing a master measure in one of it's measure expressions (not linked otherwise though) 

IE:
![image](https://user-images.githubusercontent.com/10905802/155183001-c58dc634-8b91-4a53-8b5e-5fc10bfb953c.png)

2. Check the output hypercube data, data for measures that are referencing master measures by name in their expression will output nulls instead of the correct values

Example Output When Calling getHypercube Data With Enigma:
![image](https://user-images.githubusercontent.com/10905802/155184082-6a237910-daab-40c5-84ff-e52cf44f81dc.png)

##### Expected behavior

I would expect this to behave like it does when working with the Engine API Explorer in the Dev Hub for the same App/Object pair - data should be returned for these columns. 

Example of Correct Behavior Demonstrated in Engine API Explorer (Using Same App & Object - looking at the same row as in the above example):
![image](https://user-images.githubusercontent.com/10905802/155184331-a45f839a-4afe-45a5-9161-7b6881e4d670.png)

##### Additional Information

I added some interceptors so we could see the request before it's being sent to the engine and preview the response before we ingest it:
![image](https://user-images.githubusercontent.com/10905802/155192569-3b1f8299-eecb-4cf2-9bda-b809a142b7a4.png)

##### Library
```
[x] Node.js
[] Browser
```
##### Operating system
```
[x] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[x] Desktop
[x] Enterprise
```
### Versions
* Enigma: 2.7.3
* Node.js: 16.9.0
* Browser: Chrome
* Qlik Sense: Feb 2021 (Both Desktop & Enterprise)

**Comment by aihazm** [comment] 2022-03-10 11:44
Hi @tomomni,
We unfortunately couldn't reproduce this issue, but one of my colleagues suggested that this can be a permission issue: that maybe the authenticated user in node.js/enigma is not the same as the one authenticated via browser (dev-hub)

**Comment by tomomni** [comment] 2022-03-10 15:29
Hi @aihazm,

Thanks for checking this out, it's a really peculiar issue since there is no problem when using linked master measures it only occurs when referencing master measures in a measure expression. 

When connecting to an enterprise environment, I am basically running my app as an SSE - on the server using the site certificates for authentication, my user in this case is typically the env service account. 

I could see the potential for a permission mismatch issue here however, it's odd that a permissions issue would allow me to get data from adjacent columns in the same visualization (table). Furthermore, I can also recreate the issue when running locally using Sense Desktop too both when I have provided my user/directory info and when I leave it null.

I will take a closer look here, toy around with my user/directory settings and update this post with my findings.

Additionally, would it help if I share a repo with a re-creatable Sense Desktop example (including the QVF)? I can whip something up relatively quickly if you guys will check it out. 

Thanks again for looking into this.

-Tom

**Comment by wennmo** [comment] 2022-04-06 07:34
Hi @tomomni ,
My apologies for the late follow-up. Thank you for the provided example of reproducing the issue. I am now looking into the issue, and think I have found the cause of the problem that you are experiencing. 

Just for confirmation, with your example app & script provided you are getting the following result for `getHyperCubeData`?

<img width="659" alt="Screenshot 2022-04-05 at 15 57 17" src="https://user-images.githubusercontent.com/18258091/161920243-e3add3cc-795c-4058-af48-5465caff446a.png">

And expected behaviour would be :

<img width="652" alt="Screenshot 2022-04-05 at 15 56 56" src="https://user-images.githubusercontent.com/18258091/161920380-fcbea223-f2a7-419b-9ec0-716258210bf6.png">

**Comment by wennmo** [comment] 2022-04-07 06:31
Hi @tomomni, thanks for the confirmation. This problem has already been fixed in Qlik Sense SaaS, which is why @aihazm was unable to reproduce it. 

Since you are testing against Qlik Sense Enterprise/Desktop Feb 2021, I will look into when/if the solution was introduced for those products.

**Comment by tomomni** [comment] 2022-04-11 19:43
@wennmo, interesting that it's solved in SaaS. 

I thought @aihazm might not have been able to recreate the issue because I missed exactly what the trigger was initially - it was only in assembling my example that I realized the issue can only be triggered when the master measure has it's own label expression and the column where the master measure is being referenced has it's own label (like in the example app). 

I just tested using enterprise Feb 2022 Patch 2 and the issue still exists as of that version.

**Comment by wennmo** [comment] 2022-04-27 08:23
@tomomni, sorry for the delay but now I finally got a response on when the fix was introduced.

Since Qlik Sense Enterprise for Windows has a different release cadence compared to Qlik Sense SaaS, it has so far not been part of any release. It is however targeted for the May release (but was not part of the February release).

**Comment by wennmo** [comment] 2022-05-09 07:40
I will close this issue for now, since this is not `enigma.js` related.

There is a fix being planned for the next release of Qlik Sense Enterprise for Windows, and that should resolve the issue.

**Closed by wennmo** 2022-05-09 07:40 UTC
