### ISSUE TITLE
Broken link to Authentication Examples

### ISSUE THREAD

**Issue by mcgovey** [qlik-oss/enigma.js#149] opened 2017-07-21 18:40 UTC
### Description

Broken link and/or missing examples of possible authentication methods.

### Steps to Reproduce

1. Go to [Authentication overview](https://github.com/qlik-oss/enigma.js/blob/master/docs/concepts.md#authentication)
2. Click [Authentication Examples](https://github.com/qlik-oss/enigma.js/blob/master/examples/authentication)

##### Expected behavior

Repository of authentication examples while leveraging Enigma.js

##### Actual behavior

404 Missing Page

**Comment by marcusoffesson** [comment] 2017-07-24 21:23
Thanks! Examples are still left to be done for v2.

**Comment by marcusoffesson** [comment] 2017-07-25 18:04
(Duplicate of #125 and #126.)

**Closed** 2017-07-25 18:04 UTC
Labels: v2
