### ISSUE TITLE
Socket closed in chrome but working fine in Edge browser enigma js + qlik sense

### ISSUE THREAD

**Issue by hshahul** [qlik-oss/enigma.js#795] opened 2020-09-11 12:32 UTC
Hi Team,

I am trying to connect Qlik sense with Enigma js, it is working fine in Edge browse but not working in chrome browser. I am getting the following error. 

Uncaught (in promise) 
code: -1
message: "Socket closed"

can you please suggest have any special settings needed for chrome

**Comment by axelssonHakan** [comment] 2020-09-14 07:58
Could you please provide some more information.

Any code example? Any more logging?

**Comment by hshahul** [comment] 2020-09-18 12:51
No logs, i am getting socket close error only. I am using our sample qlik connect code only.

const enigma = require('enigma.js');
const WebSocket = require('ws');
const schema = require('enigma.js/schemas/12.170.2.json');

// create a new session:
const session = enigma.create({
schema,
url: 'ws://localhost:9076/app/engineData',
createSocket: url => new WebSocket(url),
});


Error:
code: -1
message: "Socket closed"
proto: Object

but I am able to get connect and data from Qlik in edge browser,

Previously it is working in chrome browser, now only facing the issue ..........( no code change)

**Comment by axelssonHakan** [comment] 2020-09-18 13:03
What is different between this issue and #800 ???

If you are using web browsers is usually best to use the WebSocket API that's included in the browser (don't require `ws`)
How do you transpile your code?

**Comment by hshahul** [comment] 2020-09-18 13:06
both are same issue only.

I tried wss / ws also, but not working fine.  can you please websocket API sample code.

**Comment by axelssonHakan** [comment] 2020-09-18 13:07
Are you using Qlik Sense Desktop?

**Comment by axelssonHakan** [comment] 2020-09-18 13:08
> both are same issue only.
> 
> I tried wss / ws also, but not working fine. can you please websocket API sample code.

see #800

**Comment by axelssonHakan** [comment] 2020-09-18 13:10
Duplicate of #800

**Closed by axelssonHakan** 2020-09-18 13:10 UTC
Labels: cla signed, question/discussion

**Comment by hshahul** [comment] 2020-09-18 13:11
I am using Qlik web only

**Comment by axelssonHakan** [comment] 2020-09-18 13:27
In your code you are trying to connect to localhost:9076
`url: 'ws://localhost:9076/app/engineData',`

You need to use the URL for the web deployment and also configure web-integration
https://github.com/qlik-oss/web-integration-examples

**Comment by hshahul** [comment] 2020-09-18 13:56
I am using web url api only, for sample,i gave the sample code. except localhost, everything same only. but no luck.
